### ISSUE TITLE
commercial dimmer with ESP32

### ISSUE THREAD

**Issue by mide1337** [mkgeiger/mqtt-dimmer#1]
Hello,
how did you find out about the ingredients of the NX-4653-901? I want to lookout for the same one but maybe with an esp32. I would appreciate your help on that matter. Sorry for the issue here, I did not find another way to contact you.
Thanks in advance.

**Comment by mkgeiger** [comment]
Hi. I opened several devices from Luminea (LED stripe controllers, plugs, dimmers, etc.) in the past, always having inside a ESP8266 derivate. Sometimes you can find some infos in chats that a device is compatible with Tasmota-SW. This is always a hint that it has an ESP8266. For this model of dimmer and just opened, and voila, it was as expected an ESP8266. The infos and commands for the STM8S00F3 MCU I found then in a chat discussion.

**Comment by mide1337** [comment]
Thanks for the intel. I am going to try with the NX-4653-901.
